// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/storage/storage.go
//
// Generated by this command:
//
//	mockgen -source=pkg/storage/storage.go -destination=pkg/storage/mocks/storage.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	storage "github.com/anyvoxel/vela/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockStorage) Put(ctx context.Context, results []*storage.SummaryResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, results)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockStorageMockRecorder) Put(ctx, results any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockStorage)(nil).Put), ctx, results)
}

// SummaryExists mocks base method.
func (m *MockStorage) SummaryExists(ctx context.Context, path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SummaryExists", ctx, path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SummaryExists indicates an expected call of SummaryExists.
func (mr *MockStorageMockRecorder) SummaryExists(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SummaryExists", reflect.TypeOf((*MockStorage)(nil).SummaryExists), ctx, path)
}
