name: on-pr-opened

on:
    pull_request:
        types: [opened]

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v3
              with:
                  go-version: "1.25"
            - run: |
                  echo "Pull Request ID: ${{ github.event.pull_request.id }}"
                  echo "Pull Request URL: ${{ github.event.pull_request.url }}"
                  go version
