name: on-pr-opened

on:
  issues:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.25"
      - name: test
        run: |
          echo "Pull Request ID: ${{ github.event.issue.id }}"
          echo "Pull Request URL: ${{ github.event.issue.url }}"
          go version
          go mod download
      - name: summary
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}
          OPENAI_BASE_URL: ${{ vars.OPENAI_BASE_URL }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          go run main.go
      - name: Commit changes
        run: |
          git config --global user.email "${{ vars.EMAIL }}"
          git config --global user.name "${{ vars.NAME }}"
          git checkout -b feat-$(date -u '+%Y-%m-%d')
          git add .
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "update: $(date -u '+%Y-%m-%d') blog posts"
          echo "Changes committed"
          git checkout main
          git remote -v
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: feat-$(date -u '+%Y-%m-%d')
          title: "feat: $(date -u '+%Y-%m-%d') blog posts"
          body: "Update $(date -u '+%Y-%m-%d') blog posts"
          commit-message: "update: $(date -u '+%Y-%m-%d') blog posts"
