name: on-pr-opened

on:
    issues:
        types: [opened]

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v3
              with:
                  go-version: "1.25"
            - name: test
              run: |
                  echo "Pull Request ID: ${{ github.event.issue.id }}"
                  echo "Pull Request URL: ${{ github.event.issue.url }}"
                  go version
                  go mod download
            - name: summary
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
                  OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
                  GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
              run: |
                  go run main.go
